--- 
# i3 Window Manager installation playbook 
# This playbook installs the i3 window manager from the sur5r repository, 
# along with related tools like nitrogen and rofi. i3 as an uncomposited X11
# desktop can fix some issues with PTB, and you can remove all
# touchable/clickable GUI to minimise subects altering some OS functions. -
- name: Install i3 Window Manager 
  hosts: all 
  become: true 
  gather_facts: true

  tasks:
    - name: Download sur5r keyring deb
      ansible.builtin.get_url:
        url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.12.14_all.deb keyring.deb
        dest: /tmp/sur5r-keyring.deb
        checksum: sha256:2c816fbd12ea4d84811818aed0ce3a5da589be1afa30833eb32abc1e4fe6349e
        mode: '0644'

    - name: Install sur5r keyring
      ansible.builtin.apt:
        deb: /tmp/sur5r-keyring.deb

    - name: Add sur5r i3 repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/sur5r-keyring.gpg] http://debian.sur5r.net/i3/ {{ ansible_facts['distribution_release'] }} universe"
        filename: sur5r-i3
        state: present
        update_cache: true

    - name: Install i3
      ansible.builtin.apt:
        name:
          - i3
          - nitrogen
          - rofi
        state: present

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Cleanup temporary keyring file
      ansible.builtin.file:
        path: /tmp/sur5r-keyring.deb
        state: absent
