---
# Ansible playbook to force reset CageLab code repositories to their latest
# upstream state. If you don't do this, uncommitted changes or local branches
# will prevent updates and this machine dependent variance is hard to debug.
- name: Reset CageLab Code Repositories
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  ignore_unreachable: true

  vars:
    repositories: # List of repositories to reset and update
      - { path: '~/Code/Setup', url: 'https://gitee.com/CogPlatform/Setup.git' }
      - { path: '~/Code/CageLab', url: 'https://gitee.com/CogPlatform/CageLab.git' }
      - { path: '~/Code/Psychtoolbox', url: 'https://gitee.com/CogPlatform/Psychtoolbox.git' }
      - { path: '~/Code/opticka', url: 'https://gitee.com/CogPlatform/opticka.git' }
      - { path: '~/Code/matmoteGO', url: 'https://gitee.com/CogPlatform/matmoteGO.git' }
      - { path: '~/Code/PTBSimia', url: 'https://gitee.com/CogPlatform/PTBSimia.git' }
      - { path: '~/Code/matlab-jzmq', url: 'https://gitee.com/CogPlatform/matlab-jzmq.git' }
      - { path: '~/Code/PacmanTask', url: 'https://gitee.com/CogPlatform/PacmanTask.git' }
      - { path: '~/.dotfiles', url: 'https://codeberg.org/iandol/dotfiles.git' }

  tasks:
    - name: Reset and update repositories
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ item.path | regex_replace('^~', ansible_facts['user_dir']) }}"
        version: 'HEAD'
        force: true
        accept_hostkey: true
      environment:
        GIT_TERMINAL_PROMPT: '0'
      loop: "{{ repositories }}"

    - name: Clean untracked files from repositories
      ansible.builtin.command:
        argv:
          - git
          - clean
          - -fdx
      args:
        chdir: "{{ item.path | regex_replace('^~', ansible_facts['user_dir']) }}"
      loop: "{{ repositories }}"
      register: repo_clean
      changed_when: repo_clean.stdout != ''
