---
# Ansible playbook to set up MATLAB startup file and add necessary paths and preferences
- name: Setup MATLAB startup file
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure MATLAB Documents directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/Documents/MATLAB'
        state: directory
        mode: '0755'

    - name: Check if startup.m exists
      ansible.builtin.stat:
        path: '{{ ansible_env.HOME }}/Documents/MATLAB/startup.m'
      register: startup_file

    - name: Create startup.m if it does not exist
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/Documents/MATLAB/startup.m'
        state: touch
        mode: '0644'
      when: not startup_file.stat.exists

    - name: Add addOptickaToPath to startup.m
      ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/Documents/MATLAB/startup.m'
        line: 'addOptickaToPath;'
        state: present

    - name: Add addOptickaToPath to startup.m
      ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/Documents/MATLAB/startup.m'
        line: 'Screen(''Preference'', ''VisualDebugLevel'', 3);'
        state: present
